apiVersion: apps/v1
kind: Deployment
metadata:
  name: canteen-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canteen-frontend
  template:
    metadata:
      labels:
        app: canteen-frontend
    spec:
      containers:
      - name: canteen-frontend
        image: canteen-frontend:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: canteen-frontend
spec:
  selector:
    app: canteen-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
