apiVersion: apps/v1
kind: Deployment
metadata:
  name: canteen-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canteen-java
  template:
    metadata:
      labels:
        app: canteen-java
    spec:
      containers:
      - name: canteen-java
        image: canteen-java:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: canteen-java
spec:
  selector:
    app: canteen-java
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
