spring:
  application:
    name: canteen-analysis
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/back_end?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: ""       # Redis 密码（无密码则留空）
      database: 0        # 连接的 Redis 数据库索引（默认0）
      timeout: 3000      # 连接超时时间（毫秒）
      lettuce: # 使用 Lettuce 客户端（Spring Boot 2.x 后默认）
        pool:
          max-active: 8  # 最大连接数
          max-idle: 8    # 最大空闲连接数
          min-idle: 2    # 最小空闲连接数
  cache:
    type: redis        # 指定缓存类型为 Redis
    redis:
      time-to-live: 0  # 过期时间0小时，单位毫秒

server:
  port: 8080
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
    xyz.mambaout.canteenanalysis.mapper: DEBUG

